POST http://localhost:5050/posts
Content-Type: application/json

{
    "title":"What's New?",
    "postType":"post",
    "slug":"new-with-nestxjs",
    "status":"draft",
    "content":"test content",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\":\"Person\"\r\n}",
    "featuredImage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZ8W_3wEcaamswDUWW6J2OoiEKzKzyR8NgA&s",
    "publishedOn":"2024-07-01T00:00:00.000",
    "tags":["nestjs","nodejs","javascript"],
    "metaOptions":[{
        "key":"What's New?",
        "value":"What's new with NestJS"
    }]
}